#!/usr/bin/env python

import datetime, subprocess, os
from numpy import *
from pylab import *
from mpl_toolkits.basemap import Basemap
import netCDF4 



#-----------------------------------------------------------------------
y = ['01','02','03','04','05','06','07','08','09','10','11','12']
for m in y:
#for m in range(0,13):

   i = [26,45,60,85]
   for c in i:
   
      def make_animation():

         cmd = ['convert', '-delay', '20', '-loop', '1', './test/tasmax_ens-avg_amon_rcp'+str(c)+'*'+str(m)+'.png', './ani/animation_rcp'+str(c)+'_'+str(m)+'.gif']
         subprocess.call(cmd)
#make_animation



#-----------------------------------------------------------------------
      if __name__ == '__main__':

         print "Working on month "+str(m)+" animations..."
         make_animation()

#__main__



